trigger:  
- master  
  
pool:  
  vmImage: 'ubuntu-latest'  
  
steps:  
- task: NodeTool@0  
  inputs:  
    versionSpec: '12.x'  
  displayName: 'Install Node.js 12.x'  
- task: Npm@1  
  displayName: 'Angular CLI'  
  inputs:  
    command: custom  
    verbose: false  
    customCommand: 'install @angular/cli@7.3.1'  
- task: Npm@1  
  displayName: 'npm install'  
  inputs:  
    verbose: false  